<html>
<head>
<title></title>
</head>
<body bgcolor="#ffffd">
<form name="f1" method="post" action="http:\\localhost:7000\examples\jsp\krishna\ser.jsp">
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<font face="Book Antiqua" size="4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<u>SERVER INFORMATION </u></font></h1>
  <div align="center"><div align="center"><center><table align="center">
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>SERVER CODE</strong></font></td>
      <td><input box="text" name="T1" size="20"></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>SERVER NAME</strong></font></td>
      <td><input box="text" name="T2" size="20"></td>
    </tr>
    <tr>
      <td width="50%"><font face="Arial" size="3" color="#800080"><strong>SERVER TYPE</strong></font></td>
      <td><input type="radio" name="R1" value="NT">NT</td>
      <td><input type="radio" name="R1" value="LINUX">LINUX</td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>SERVER SIZE</strong></font></td>
      <td><input type="text" name="T3" size="20"></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>SERVER LOCATION</strong></font></td>
      <td><input type="text" name="T4" size="20"></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>COMPANY</strong></font></td>
      <td><input type="text" name="T5" size="20"></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>AUTHORITY</strong></font></td>
      <td><select name="D1" size="1">
        <option value="manager">MANAGER</option>
        <option value="director">DIRECTOR</option>
        <option value="chairman">CHAIRMAN</option>
        <option value="soft">SOFTWARE ENGINEER</option>
      </select></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>ADDRESS</strong></font></td>
      <td style="font-family: Arial; font-size: 14; color: rgb(128,0,128)"><input type="text"
      name="T6" size="20"></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>PHONE NUMBER</strong></font></td>
      <td><input type="text" name="T7" size="20"></td>
    </tr>
    <tr>
      <td><font face="Arial" size="3" color="#800080"><strong>MAIL ID</strong></font></td>
      <td><input type="text" name="T8" size="20"></td>
    </tr>
  </table>
  </center></div>
  <dd align="center">&nbsp;</dd>
  <dd align="center"><input type="submit" name="s1" value="SUBMIT"> <input type="reset"
    name="r1" value="RESET"> </dd>
  </div>
</form>

</BODY>
</HTML>
